### ISSUE TITLE
so-novel v1.5.3 版本 搜索小说链接超时

### ISSUE THREAD

**Issue by xshuaiq1** [pcdd-group/so-novel#6]
+－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－+
|　 so-novel v1.5.3  　　　　　　　　　　　　　　　　　|
|　当前书源：https://www.xbiqugu.info　　　　　　　　　　　　　　　|
|　导出格式：epub　　　　　　　　　　　　　　　　　　　　　|
+－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－+
|　使用须知　　　　　　　　　　　　　　　　　　　　　　　　　　　　|
|　1. 下载受书源、网络等因素影响，若下载失败可尝试增大爬取间隔 　　|
|　2. 请按要求输入，然后按回车（Enter）执行　　　　　　　　　　　　|
|　3. 可输入 exit 结束程序 　　　　　　　　　　　　　　　　　　　　|
+－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－+
==> 请输入书名或作者：
遮天   
<== 正在搜索...
Exception in thread "main" java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:848)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:876)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:818)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:346)
        at org.jsoup.helper.HttpConnection.post(HttpConnection.java:339)
        at com.pcdd.sonovel.parse.SearchResultParser.parse(SearchResultParser.java:30)
        at com.pcdd.sonovel.core.Crawler.search(Crawler.java:75)
        at com.pcdd.sonovel.Main.main(Main.java:40)

**Comment by pcdd-group** [comment]
用最新版

**Comment by xshuaiq1** [comment]
最新版没有mac版本啊

**Comment by pcdd-group** [comment]
> 最新版没有mac版本啊

mac 下载 jre 版本即可，用 java.exe 启动 jar 文件。
实在不会等晚上上传 mac 版本

**Comment by pcdd-group** [comment]
> 最新版没有mac版本啊

晚上发布下mac版本

**Comment by xshuaiq1** [comment]
嗯 每次新下载的包都需要给run.sh 和 jre的java执行权限才能运行,这个有办法优化下吗

**Comment by pcdd-group** [comment]
已上传：https://github.com/pcdd-group/so-novel/releases/tag/v1.5.4.1
这边无 mac 环境，你测试下
